name: Deploy Frontend
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t reidtaylor/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true reidtaylor/react-test npm test
 
      - name: Generate deployment image for client
        run: docker build -t reidtaylor/multi-client ./client
 
      - name: Generate deployment images for nginx
        run: docker build -t reidtaylor/multi-nginx ./nginx
 
      - name: Generate deployment images for server 
        run: docker build -t reidtaylor/multi-server ./server
 
      - name: Generate deployment images for worker
        run: docker build -t reidtaylor/multi-worker ./worker

      - name: Connect to Docker CLI
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
 
      - name: Push Client to Docker
        run: docker push reidtaylor/multi-client
 
      - name: Push Nginx to Docker
        run: docker push reidtaylor/multi-nginx
 
      - name: Push Server to Docker
        run: docker push reidtaylor/multi-server
 
      - name: Push Worker to Docker
        run: docker push reidtaylor/multi-worker
      
      - name: Generate deployment package
        run: zip -r deploy.zip ./docker-compose.yml
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-multi-app
          environment_name: Dockermultiapp-env
          existing_bucket_name: elasticbeanstalk-us-east-2-375234172965
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip

      - name: logout of Docker for added security
        run: docker logout
